name: docrunner
description: A command line tool which allows you to run the code in your markdown files to ensure that readers always have access to working code.
version: 0.1.9
homepage: https://github.com/DudeBro249/docrunner

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  colorize: ^3.0.0
  json_annotation: ^4.0.1
  path: ^1.8.0
  toml: ^0.11.0



dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  pedantic: ^1.9.0
  test: ^1.14.4
