name: docrunner
description: A command line tool which allows you to run the code in your markdown files to ensure that readers always have access to working code.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies: 



dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
